# Generated by Django 5.1.1 on 2024-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id_mem', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_cliente', models.PositiveIntegerField()),
                ('duracion', models.PositiveIntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuentos', models.CharField(max_length=100)),
            ],
        ),
    ]
