# Generated by Django 5.1.1 on 2024-12-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('id_entrenador', models.PositiveIntegerField()),
                ('nombre_clase', models.CharField(max_length=50)),
                ('horario', models.CharField(max_length=100)),
                ('capacidad', models.PositiveIntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
